# Generated by Django 5.1.5 on 2025-02-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('zodiac', models.CharField(choices=[('Aries', 'Aries - Compatible with Leo, Sagittarius'), ('Taurus', 'Taurus - Compatible with Virgo, Capricorn'), ('Gemini', 'Gemini - Compatible with Libra, Aquarius'), ('Cancer', 'Cancer - Compatible with Scorpio, Pisces'), ('Leo', 'Leo - Compatible with Aries, Sagittarius'), ('Virgo', 'Virgo - Compatible with Taurus, Capricorn'), ('Libra', 'Libra - Compatible with Gemini, Aquarius'), ('Scorpio', 'Scorpio - Compatible with Cancer, Pisces'), ('Sagittarius', 'Sagittarius - Compatible with Aries, Leo'), ('Capricorn', 'Capricorn - Compatible with Taurus, Virgo'), ('Aquarius', 'Aquarius - Compatible with Gemini, Libra'), ('Pisces', 'Pisces - Compatible with Cancer, Scorpio')], max_length=20)),
            ],
        ),
    ]
