# Generated by Django 5.1.5 on 2025-02-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_zodiac'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='match_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='user.userprofile'),
        ),
    ]
