# Generated by Django 5.1.5 on 2025-02-05 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='matched_with', to='user.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by', to='user.userprofile'),
        ),
    ]
