# Generated by Django 5.1.5 on 2025-02-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rejected_matches',
            field=models.ManyToManyField(blank=True, related_name='rejected_by', to='user.userprofile'),
        ),
    ]
